# -*- coding: utf-8 -*-
from fastapi import APIRouter, Depends, HTTPException, Query, Response, status
from sqlalchemy.orm import Session
from typing import Optional
from datetime import datetime
import re
from ..database import engine, get_db
from ..models import Journal, Article
from ..services.markdown_normalize import normalize_markdown_text

router = APIRouter(prefix="/api", tags=["articles"])


# ===== Pandoc residue sanitizer (read path) =====
# Article content is generated by pandoc from .docx sources. Some artifacts
# leak through as raw Markdown, e.g.
#   **[自动驾驶接驳实践研究]**
#   [**摘要：** ...]
#   [段落正文]
#   {#sec:foo .unnumbered}
#   ![](media/image1.png){width="6.5in" height="3.5in"}    ← pandoc image attrs
#
# This sanitizer now delegates to `normalize_markdown_text` (single source of
# truth — shared with the .docx import path and the offline migration).
# `rewrite_images=False` because the article body is already stored with
# absolute `/uploads/source-images/...` URLs (slug-based path rewrite was done
# at import time).
def _sanitize_markdown(text: Optional[str], *, slug: Optional[str] = None) -> Optional[str]:
    if not text:
        return text
    return normalize_markdown_text(text, slug=slug, rewrite_images=False)


def _sanitize_summary(text: Optional[str]) -> Optional[str]:
    if not text:
        return text
    # Summaries are short, so the leading [...] emphasis span is almost always
    # a pandoc artifact. Drop it.
    text = re.sub(r"^\s*\*+\s*\[([^\]\n]+?)\]\s*\*+\s*", "", text)
    text = re.sub(r"^\s*\[([^\]\n]+?)\]\s*", "", text)
    text = re.sub(r"\{[#.=][^\n\}]*\}", "", text)
    return text.strip()

def _list_journals_impl(db: Session):
    """Public list — only published journals."""
    journals = (
        db.query(Journal)
        .filter(Journal.status == "published")
        .order_by(Journal.published_at.desc())
        .all()
    )
    return [_journal_to_dict(j) for j in journals]


def _get_journal_impl(db: Session, slug: str):
    """Public detail — 404 for drafts."""
    journal = (
        db.query(Journal)
        .filter(Journal.slug == slug, Journal.status == "published")
        .first()
    )
    if not journal:
        raise HTTPException(status_code=404, detail="期刊不存在")
    return _journal_to_dict(journal, include_articles=True)


@router.get("/journals")
def get_journals(db: Session = Depends(get_db)):
    """获取期刊列表 (alias for GET /issues)."""
    return _list_journals_impl(db)


@router.get("/journals/{slug}")
def get_journal(slug: str, db: Session = Depends(get_db)):
    """获取期刊详情 (alias for GET /issues/{slug})."""
    return _get_journal_impl(db, slug)

@router.get("/articles")
def get_articles(
    category: Optional[str] = Query(None),
    journal_slug: Optional[str] = Query(None),
    page: int = Query(1, ge=1),
    per_page: int = Query(10, ge=1, le=50),
    db: Session = Depends(get_db),
):
    """获取文章列表"""
    query = db.query(Article).filter(Article.status == "published")

    if category:
        query = query.filter(Article.category == category)
    if journal_slug:
        query = query.join(Journal).filter(Journal.slug == journal_slug)

    total = query.count()
    articles = query.order_by(Article.published_at.desc()).offset((page-1)*per_page).limit(per_page).all()

    return {
        "items": [
            {
                "id": a.id,
                "title": a.title,
                "slug": a.slug,
                "summary": _sanitize_summary(a.summary),
                "cover_image": a.cover_image,
                "category": a.category,
                "author_name": a.author_name,
                "reading_time": a.reading_time,
                "views": a.views,
                "tags": a.tags.split(",") if a.tags else [],
                "published_at": a.published_at.isoformat() if a.published_at else None
            }
            for a in articles
        ],
        "total": total,
        "page": page,
        "per_page": per_page,
        "pages": (total + per_page - 1) // per_page
    }


@router.get("/articles/featured")
def get_featured_articles(db: Session = Depends(get_db)):
    """获取精选文章"""
    articles = db.query(Article).filter(Article.featured == 1, Article.status == "published").order_by(Article.published_at.desc()).limit(3).all()
    return [
        {
            "id": a.id,
            "title": a.title,
            "slug": a.slug,
            "summary": _sanitize_summary(a.summary),
            "cover_image": a.cover_image,
            "category": a.category,
            "author_name": a.author_name,
            "reading_time": a.reading_time,
            "views": a.views,
            "published_at": a.published_at.isoformat() if a.published_at else None
        }
        for a in articles
    ]


@router.get("/articles/{slug}")
def get_article(slug: str, db: Session = Depends(get_db)):
    """获取文章详情"""
    article = db.query(Article).filter(Article.slug == slug, Article.status == "published").first()
    if not article:
        raise HTTPException(status_code=404, detail="文章不存在")

    related = db.query(Article).filter(
        Article.category == article.category,
        Article.id != article.id
    ).limit(3).all()

    return {
        "id": article.id,
        "title": article.title,
        "slug": article.slug,
        "content": _sanitize_markdown(article.content, slug=article.slug),
        "summary": _sanitize_summary(article.summary),
        "cover_image": article.cover_image,
        "category": article.category,
        "author_name": article.author_name,
        "author_avatar": article.author_avatar,
        "reading_time": article.reading_time,
        "views": article.views,
        "tags": article.tags.split(",") if article.tags else [],
        "published_at": article.published_at.isoformat() if article.published_at else None,
        "related": [
            {
                "id": r.id,
                "title": r.title,
                "slug": r.slug,
                "summary": _sanitize_summary(r.summary),
                "category": r.category,
                "reading_time": r.reading_time
            }
            for r in related
        ]
    }


@router.post("/articles/{slug}/view", status_code=status.HTTP_204_NO_CONTENT)
def increment_view(slug: str, db: Session = Depends(get_db)):
    """Increment article view count. Idempotent on missing article (still 204)."""
    article = db.query(Article).filter(Article.slug == slug).first()
    if article:
        article.views = (article.views or 0) + 1
        db.commit()
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@router.get("/categories")
def get_categories():
    """获取文章分类列表"""
    db = Session(bind=engine)
    try:
        articles = db.query(Article.category).distinct().all()
        return [a[0] for a in articles if a[0]]
    finally:
        db.close()


# =====================================================================
# /api/issues — multi-issue (multi-journal) endpoints
#
# /api/journals is kept for backward compatibility (returns the same data
# as /api/issues). New consumers should prefer /api/issues.
# =====================================================================

def _journal_to_dict(journal: Journal, include_articles: bool = False):
    """Serialize a Journal row to a JSON-friendly dict.

    If `include_articles` is True, also serializes the bound articles using
    the same shape as /journals/{slug} so callers don't need a second round
    trip.
    """
    payload = {
        "id": journal.id,
        "title": journal.title,
        "slug": journal.slug,
        "cover_image": journal.cover_image,
        "description": journal.description,
        "issue_number": journal.issue_number,
        "published_at": journal.published_at.isoformat() if journal.published_at else None,
        "article_count": len(journal.articles),
    }
    if include_articles:
        payload["articles"] = [
            {
                "id": a.id,
                "title": a.title,
                "slug": a.slug,
                "summary": _sanitize_summary(a.summary),
                # cover_image MUST be included — IssueDetail.tsx renders ArticleCard which feeds it
                # to <CoverImage>. If the field is missing, src becomes undefined and every card
                # falls back to the blue gradient placeholder (user reported as "白色 / 白屏").
                "cover_image": a.cover_image,
                "category": a.category,
                "author_name": a.author_name,
                "reading_time": a.reading_time,
                "views": a.views,
                "tags": a.tags.split(",") if a.tags else [],
                "published_at": a.published_at.isoformat() if a.published_at else None,
            }
            for a in sorted(journal.articles, key=lambda x: x.published_at or datetime.min, reverse=True)
        ]
    return payload


@router.get("/issues")
def get_issues(db: Session = Depends(get_db)):
    """List all journal issues, sorted by published_at desc."""
    return _list_journals_impl(db)


@router.get("/issues/{slug}")
def get_issue(slug: str, db: Session = Depends(get_db)):
    """Issue detail with all its articles, sorted by published_at desc."""
    return _get_journal_impl(db, slug)


@router.get("/issues/{slug}/articles")
def get_issue_articles(slug: str):
    """All articles in a given issue, sorted by published_at desc."""
    db = Session(bind=engine)
    try:
        journal = db.query(Journal).filter(Journal.slug == slug).first()
        if not journal:
            raise HTTPException(status_code=404, detail="期刊不存在")

        articles = sorted(
            journal.articles,
            key=lambda a: a.published_at or datetime.min,
            reverse=True,
        )
        return {
            "issue": {
                "id": journal.id,
                "slug": journal.slug,
                "title": journal.title,
                "issue_number": journal.issue_number,
                "published_at": journal.published_at.isoformat() if journal.published_at else None,
            },
            "items": [
                {
                    "id": a.id,
                    "title": a.title,
                    "slug": a.slug,
                    "summary": _sanitize_summary(a.summary),
                    "cover_image": a.cover_image,
                    "category": a.category,
                    "author_name": a.author_name,
                    "reading_time": a.reading_time,
                    "views": a.views,
                    "tags": a.tags.split(",") if a.tags else [],
                    "published_at": a.published_at.isoformat() if a.published_at else None,
                }
                for a in articles
            ],
            "total": len(articles),
        }
    finally:
        db.close()
