# -*- coding: utf-8 -*-
from fastapi import APIRouter, Depends, HTTPException, Query, Response, status
from sqlalchemy.orm import Session
from typing import Optional
from datetime import datetime
import re
from ..database import engine, get_db
from ..models import Journal, Article

router = APIRouter(prefix="/api", tags=["articles"])


# ===== Pandoc residue sanitizer =====
# Article content is generated by pandoc from .docx sources. Some artifacts
# leak through as raw Markdown, e.g.
#   **[自动驾驶接驳实践研究]**
#   [**摘要：** ...]
#   [段落正文]
#   {#sec:foo .unnumbered}
#
# This sanitizer (read path) strips the most common pandoc residue so the
# public read API always returns clean Markdown. It mirrors the offline
# `scripts/normalize_markdown.py` pass but is intentionally simpler — it
# catches only the residue that breaks rendering. Heavy lifting (full-width
# punctuation, plain-table conversion, image-path rewriting) is done
# offline; see `scripts/normalize_markdown.py`.
def _sanitize_markdown(text: Optional[str]) -> Optional[str]:
    if not text:
        return text
    # 1. Drop pandoc attribute blocks {...} (NOT cross-line: { matches } on the same line)
    text = re.sub(r"\{[#.=][^\n\}]*\}", "", text)
    # 2. Unwrap [...]{.mark} BEFORE stripping standalone {...} so the
    #    bracket-class wrapper gets matched first.
    text = re.sub(r"\[([^\]\n]+?)\]\{[#.][^\n\}]*\}", r"\1", text)
    text = re.sub(r"\{[#.=][^\n\}]*\}", "", text)
    # 3. Unwrap **\[...\]** emphasis around bracket labels. NOTE: `[ \t]*`
    #    (horizontal whitespace only) so we don't merge a heading's trailing
    #    `**` with a paragraph's leading `[` across a newline.
    text = re.sub(r"\*\*[ \t]*\[", "[", text)
    text = re.sub(r"\][ \t]*\*\*", "]", text)
    text = re.sub(r"\*\*\[([^\]\n]+?)\]\*\*", r"\1", text)
    # 4. Unwrap pandoc-escaped brackets (\\[1\\] -> [1]) so the citation links work
    text = re.sub(r"\\\[(\d+)\\\]", r"[\1]", text)
    text = re.sub(r"\\\[", "[", text)
    text = re.sub(r"\\\]", "]", text)
    # 5. Trim blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)
    # 6. Convert pandoc extended tables (`+---+` separator, `|...|...|` rows)
    #    to GFM pipe tables so react-markdown + remark-gfm can render them.
    #    Heavy work is done offline by scripts/normalize_markdown.py; this
    #    is a defensive catch for content added via the admin UI.
    text = re.sub(
        r"^\s*\+(?:[-\s]+\+)+\s*$",
        lambda _m: "|" + " | ".join(["---"] * (max(2, _m.group(0).count("+") - 1))) + " |",
        text,
        flags=re.MULTILINE,
    )
    return text.strip()


def _sanitize_summary(text: Optional[str]) -> Optional[str]:
    if not text:
        return text
    # Summaries are short, so the leading [...] emphasis span is almost always
    # a pandoc artifact. Drop it.
    text = re.sub(r"^\s*\*+\s*\[([^\]\n]+?)\]\s*\*+\s*", "", text)
    text = re.sub(r"^\s*\[([^\]\n]+?)\]\s*", "", text)
    text = re.sub(r"\{[#.=][^\n\}]*\}", "", text)
    return text.strip()

def _list_journals_impl(db: Session):
    """Shared implementation for GET /journals and GET /issues.

    Both endpoints return the same payload shape, so the actual query and
    serialization live here to avoid drift.
    """
    journals = db.query(Journal).order_by(Journal.published_at.desc()).all()
    return [_journal_to_dict(j) for j in journals]


def _get_journal_impl(db: Session, slug: str):
    """Shared implementation for GET /journals/{slug} and GET /issues/{slug}.

    Returns the serialized journal with its bound articles. Raises 404 when
    the slug does not match any journal.
    """
    journal = db.query(Journal).filter(Journal.slug == slug).first()
    if not journal:
        raise HTTPException(status_code=404, detail="期刊不存在")
    return _journal_to_dict(journal, include_articles=True)


@router.get("/journals")
def get_journals():
    """获取期刊列表 (alias for GET /issues)."""
    db = Session(bind=engine)
    try:
        return _list_journals_impl(db)
    finally:
        db.close()

@router.get("/journals/{slug}")
def get_journal(slug: str):
    """获取期刊详情 (alias for GET /issues/{slug})."""
    db = Session(bind=engine)
    try:
        return _get_journal_impl(db, slug)
    finally:
        db.close()

@router.get("/articles")
def get_articles(
    category: Optional[str] = Query(None),
    journal_slug: Optional[str] = Query(None),
    page: int = Query(1, ge=1),
    per_page: int = Query(10, ge=1, le=50),
    db: Session = Depends(get_db),
):
    """获取文章列表"""
    query = db.query(Article).filter(Article.status == "published")

    if category:
        query = query.filter(Article.category == category)
    if journal_slug:
        query = query.join(Journal).filter(Journal.slug == journal_slug)

    total = query.count()
    articles = query.order_by(Article.published_at.desc()).offset((page-1)*per_page).limit(per_page).all()

    return {
        "items": [
            {
                "id": a.id,
                "title": a.title,
                "slug": a.slug,
                "summary": _sanitize_summary(a.summary),
                "cover_image": a.cover_image,
                "category": a.category,
                "author_name": a.author_name,
                "reading_time": a.reading_time,
                "views": a.views,
                "tags": a.tags.split(",") if a.tags else [],
                "published_at": a.published_at.isoformat() if a.published_at else None
            }
            for a in articles
        ],
        "total": total,
        "page": page,
        "per_page": per_page,
        "pages": (total + per_page - 1) // per_page
    }


@router.get("/articles/featured")
def get_featured_articles(db: Session = Depends(get_db)):
    """获取精选文章"""
    articles = db.query(Article).filter(Article.featured == 1, Article.status == "published").order_by(Article.published_at.desc()).limit(3).all()
    return [
        {
            "id": a.id,
            "title": a.title,
            "slug": a.slug,
            "summary": _sanitize_summary(a.summary),
            "cover_image": a.cover_image,
            "category": a.category,
            "author_name": a.author_name,
            "reading_time": a.reading_time,
            "views": a.views,
            "published_at": a.published_at.isoformat() if a.published_at else None
        }
        for a in articles
    ]


@router.get("/articles/{slug}")
def get_article(slug: str, db: Session = Depends(get_db)):
    """获取文章详情"""
    article = db.query(Article).filter(Article.slug == slug, Article.status == "published").first()
    if not article:
        raise HTTPException(status_code=404, detail="文章不存在")

    related = db.query(Article).filter(
        Article.category == article.category,
        Article.id != article.id
    ).limit(3).all()

    return {
        "id": article.id,
        "title": article.title,
        "slug": article.slug,
        "content": _sanitize_markdown(article.content),
        "summary": _sanitize_summary(article.summary),
        "cover_image": article.cover_image,
        "category": article.category,
        "author_name": article.author_name,
        "author_avatar": article.author_avatar,
        "reading_time": article.reading_time,
        "views": article.views,
        "tags": article.tags.split(",") if article.tags else [],
        "published_at": article.published_at.isoformat() if article.published_at else None,
        "related": [
            {
                "id": r.id,
                "title": r.title,
                "slug": r.slug,
                "summary": _sanitize_summary(r.summary),
                "category": r.category,
                "reading_time": r.reading_time
            }
            for r in related
        ]
    }


@router.post("/articles/{slug}/view", status_code=status.HTTP_204_NO_CONTENT)
def increment_view(slug: str, db: Session = Depends(get_db)):
    """Increment article view count. Idempotent on missing article (still 204)."""
    article = db.query(Article).filter(Article.slug == slug).first()
    if article:
        article.views = (article.views or 0) + 1
        db.commit()
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@router.get("/categories")
def get_categories():
    """获取文章分类列表"""
    db = Session(bind=engine)
    try:
        articles = db.query(Article.category).distinct().all()
        return [a[0] for a in articles if a[0]]
    finally:
        db.close()


# =====================================================================
# /api/issues — multi-issue (multi-journal) endpoints
#
# /api/journals is kept for backward compatibility (returns the same data
# as /api/issues). New consumers should prefer /api/issues.
# =====================================================================

def _journal_to_dict(journal: Journal, include_articles: bool = False):
    """Serialize a Journal row to a JSON-friendly dict.

    If `include_articles` is True, also serializes the bound articles using
    the same shape as /journals/{slug} so callers don't need a second round
    trip.
    """
    payload = {
        "id": journal.id,
        "title": journal.title,
        "slug": journal.slug,
        "cover_image": journal.cover_image,
        "description": journal.description,
        "issue_number": journal.issue_number,
        "published_at": journal.published_at.isoformat() if journal.published_at else None,
        "article_count": len(journal.articles),
    }
    if include_articles:
        payload["articles"] = [
            {
                "id": a.id,
                "title": a.title,
                "slug": a.slug,
                "summary": _sanitize_summary(a.summary),
                "category": a.category,
                "reading_time": a.reading_time,
                "views": a.views,
                "tags": a.tags.split(",") if a.tags else [],
                "published_at": a.published_at.isoformat() if a.published_at else None,
            }
            for a in sorted(journal.articles, key=lambda x: x.published_at or datetime.min, reverse=True)
        ]
    return payload


@router.get("/issues")
def get_issues():
    """List all journal issues, sorted by published_at desc."""
    db = Session(bind=engine)
    try:
        return _list_journals_impl(db)
    finally:
        db.close()


@router.get("/issues/{slug}")
def get_issue(slug: str):
    """Issue detail with all its articles, sorted by published_at desc."""
    db = Session(bind=engine)
    try:
        return _get_journal_impl(db, slug)
    finally:
        db.close()


@router.get("/issues/{slug}/articles")
def get_issue_articles(slug: str):
    """All articles in a given issue, sorted by published_at desc."""
    db = Session(bind=engine)
    try:
        journal = db.query(Journal).filter(Journal.slug == slug).first()
        if not journal:
            raise HTTPException(status_code=404, detail="期刊不存在")

        articles = sorted(
            journal.articles,
            key=lambda a: a.published_at or datetime.min,
            reverse=True,
        )
        return {
            "issue": {
                "id": journal.id,
                "slug": journal.slug,
                "title": journal.title,
                "issue_number": journal.issue_number,
                "published_at": journal.published_at.isoformat() if journal.published_at else None,
            },
            "items": [
                {
                    "id": a.id,
                    "title": a.title,
                    "slug": a.slug,
                    "summary": _sanitize_summary(a.summary),
                    "cover_image": a.cover_image,
                    "category": a.category,
                    "author_name": a.author_name,
                    "reading_time": a.reading_time,
                    "views": a.views,
                    "tags": a.tags.split(",") if a.tags else [],
                    "published_at": a.published_at.isoformat() if a.published_at else None,
                }
                for a in articles
            ],
            "total": len(articles),
        }
    finally:
        db.close()
